name: Docker Compose Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Start Docker Compose
      run: docker compose up -d --build

    - name: Wait for services to be ready
      run: |
        docker compose exec -T db mysqladmin ping -h localhost -u root -psecret --wait
        sleep 10 # Additional wait time for all services

    - name: Run Laravel migrations
      run: docker compose exec -T backend php artisan migrate --force

    - name: Run tests (example - customize as needed)
      run: |
        # Example test commands - customize based on your actual tests
        docker compose exec -T backend php artisan test
        # docker compose exec -T frontend ng test --watch=false

    - name: Verify services
      run: |
        # Verify backend is running
        docker compose ps | grep backend | grep Up
        # Verify frontend is running
        docker compose ps | grep frontend | grep Up
        # Verify database is running
        docker compose ps | grep db | grep Up

    - name: Clean up
      if: always()
      run: docker compose down -v
