name: Docker Compose Build, Test and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Nécessaire pour git diff HEAD^ HEAD

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Start Docker Compose
      run: docker compose up -d --build

    - name: Wait for services to be ready
      run: |
        docker compose exec -T db mysqladmin ping -h localhost -u root -psecret --wait
        sleep 10 # Additional wait time for all services

    - name: Run Laravel migrations
      run: docker compose exec -T backend php artisan migrate --force

    - name: Verify services
      id: verify-services
      run: |
        # Verify backend is running
        docker compose ps | grep backend | grep Up || echo "Backend service check failed"
        # Verify frontend is running
        docker compose ps | grep frontend | grep Up || echo "Frontend service check failed"
        # Verify database is running
        docker compose ps | grep db | grep Up || echo "Database service check failed"
        echo "services_ready=true" >> $GITHUB_OUTPUT

    - name: Check for Dockerfile changes
      id: dockerfile-changes
      run: |
        changed_files=$(git diff --name-only HEAD^ HEAD || echo "")
        backend_changed=false
        frontend_changed=false
        
        if [[ "$changed_files" =~ "backend/Dockerfile" ]]; then
          echo "Backend Dockerfile changed"
          backend_changed=true
        fi
        
        if [[ "$changed_files" =~ "frontend/Dockerfile" ]]; then
          echo "Frontend Dockerfile changed"
          frontend_changed=true
        fi
        
        echo "backend_changed=$backend_changed" >> $GITHUB_OUTPUT
        echo "frontend_changed=$frontend_changed" >> $GITHUB_OUTPUT
        echo "No Dockerfile changes detected" >> $GITHUB_STEP_SUMMARY

    - name: Push Backend Image
      if: |
        github.event_name == 'push' &&
        steps.verify-services.outputs.services_ready == 'true' &&
        steps.dockerfile-changes.outputs.backend_changed == 'true'
      run: |
        docker tag $(docker compose images -q backend) ${{ secrets.DOCKER_HUB_USERNAME }}/gym-backend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gym-backend:latest
      continue-on-error: true

    - name: Push Frontend Image
      if: |
        github.event_name == 'push' &&
        steps.verify-services.outputs.services_ready == 'true' &&
        steps.dockerfile-changes.outputs.frontend_changed == 'true'
      run: |
        docker tag $(docker compose images -q frontend) ${{ secrets.DOCKER_HUB_USERNAME }}/gym-frontend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gym-frontend:latest
      continue-on-error: true

    - name: Clean up
      if: always()
      run: docker compose down -v
